AllCops:
  SuggestExtensions: false
  NewCops: enable

Lint:
  Severity: warning

Style/BlockDelimiters:
  EnforcedStyle: always_braces

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/CombinableLoops:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Naming/AsciiIdentifiers:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1
